default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dev
  password: dev
  timeout: 5000

development:
  <<: *default
  database: myarticles
test:
  <<: *default
  database: myarticles

production:
  <<: *default
  database: myarticles
